### PR TITLE
Fix Plugin Duplication

### LINKED ISSUE #292: Plugins don't get copied
When you try to copy an API, it does not carry over the set-up plugins from the original one.

### PR DESCRIPTION
**Pull request by s4nji**
This fixes the TagSelect components showing empty fields when an endpoint is cloned.

#### Ticket
https://hellofresh.atlassian.net/browse/PT-1337

Fixes #292

### CODE REVIEW

File: src/modules/selects/MultiSelect/MultiSelect.js [hunk 1]
```diff
@@ -1,25 +1,14 @@
-import React, { Component } from 'react'
+import React, { PureComponent } from 'react'
```
Comment (ivanzusko) [inline src/modules/selects/MultiSelect/MultiSelect.js]: Good job with using `PureComponent` instead of just `Component` 👍 
But in this case, as far as this is stateless component now - we don't need this to be class-based component anymore.

File: src/modules/selects/MultiSelect/MultiSelect.js [hunk 2]
```diff
@@ -1,43 +1,30 @@
...
 const propTypes = {
   options: PropTypes.arrayOf(PropTypes.object).isRequired
 }
 
-class MultiSelect extends Component {
-    state = {
-      options: this.props.options,
-      value: []
-    }
+const MultiSelect = ({ input, options, ...props }) => {
```
Comment (ivanzusko) [inline src/modules/selects/MultiSelect/MultiSelect.js]: 👍
